# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build, push and deploy container app to Azure Web App

on:
  push:
    branches:
      - master1
  workflow_dispatch:

env:
  DOCKER_IMAGE: '${{ vars.REGISTRY_SOURCE }}/${{ vars.REGISTRY_USERNAME }}/${{ vars.REGISTRY_IMAGE }}'

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.REGISTRY_SOURCE }}
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: '${{env.DOCKER_IMAGE}}:${{ github.run_number }}, ${{env.DOCKER_IMAGE}}:latest'
          file: ./Dockerfile

  dev-deployment:
    runs-on: ubuntu-latest
    needs: build-and-push
    outputs:
      DEV_URL: ${{ steps.deploy-to-webapp.outputs.webapp-url }}/actuator/health
      AZURE_APP_SERVICE_NAME: ${{ vars.AZURE_APP_SERVICE_NAME }}
    environment:
      name: 'development'
      url: "${{ steps.deploy-to-webapp.outputs.webapp-url }}/actuator/health"

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_APP_SERVICE_NAME }}
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_APP_SERVICE_UI_PUBLISH_PROFILE }}
          images: '${{env.DOCKER_IMAGE}}:${{ github.run_number }}'

  dev-deployment-test:
    name: dev-app-status-check
    runs-on: ubuntu-latest
    needs: dev-deployment
    env:
      DEV_URL: ${{needs.dev-deployment.outputs.DEV_URL}}
      AZURE_APP_SERVICE_NAME: ${{needs.dev-deployment.outputs.AZURE_APP_SERVICE_NAME}}
    environment:
      name: 'dev-test'
      url: ${{needs.dev-deployment.outputs.DEV_URL}}/api/version

    steps:
      - name: Make HTTPS request
        id: http
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" "${{ env.DEV_URL }}")
          echo "RESPONSE_HTTP_CODE=$response" >> $GITHUB_ENV
          echo $RESPONSE_HTTP_CODE
          echo $DEV_URL
          echo $AZURE_APP_SERVICE_NAME

      - name: Deploy to Azure Web App
        if: ${{ env.RESPONSE_HTTP_CODE != '200' }}
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_APP_SERVICE_NAME }}
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_APP_SERVICE_UI_PUBLISH_PROFILE }}
          images: '${{env.DOCKER_IMAGE}}:${{ vars.STABLE_VERSION }}'

      - name: Update Variable STABLE_VERSION
        if: ${{ env.RESPONSE_HTTP_CODE == '200' }}
        id: update_variable
        run: |
          VARIABLE_NAME="STABLE_VERSION"
          VARIABLE_NEW_VALUE=${{ github.run_number }}

          curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/${{ github.repository }}/actions/variables/$VARIABLE_NAME" \
          -d "{\"name\":\"$VARIABLE_NAME\",\"value\":\"$VARIABLE_NEW_VALUE\"}"  