# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Fetch Variable

on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  fetch_variable:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Variable Value
        id: fetch
        run: |
          ENVIRONMENT_NAME="development"
          VARIABLE_NAME="AZURE_APP_SERVICE_NAME"
          VARIABLE_KEY="value"

          response=$(
            curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repositories/${{ github.repository_id }}/environments/$ENVIRONMENT_NAME/variables/$VARIABLE_NAME
          )
          VARIABLE_VALUE=$(echo $response | jq -r ".$VARIABLE_KEY")
          echo "VARIABLE_VALUE=$VARIABLE_VALUE" >> $GITHUB_OUTPUT
          echo $VARIABLE_VALUE

      - name: Show Variable Value
        run: echo "The value is ${{ steps.fetch.outputs.VARIABLE_VALUE }}"
